;
; ----------------- Stereo Editor Sprites  ------------------
;

    .org $4000
    .obj "003"

;
; Sprite #0
;
    .bitmap "**************          "
    .bitmap "*            *          "
    .bitmap "*            *          "
    .bitmap "*            *          "
    .bitmap "*            *          "
    .bitmap "*            *          "
    .bitmap "*            *          "
    .bitmap "*            *          "
    .bitmap "*            *          "
    .bitmap "*            *          "
    .bitmap "*            *          "
    .bitmap "*            *          "
    .bitmap "*            *          "
    .bitmap "*            *          "
    .bitmap "*            *          "
    .bitmap "*            *          "
    .bitmap "**************          "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .byte 0
;
; Sprite #1
;
    .bitmap " ******                 "
    .bitmap "********                "
    .bitmap "********                "
    .bitmap "********                "
    .bitmap "********                "
    .bitmap "********                "
    .bitmap " ******                 "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .byte 0
;
; Sprite #2
;
    .bitmap "       ******           "
    .bitmap "     ****  ****         "
    .bitmap "     ***    ***         "
    .bitmap "     ****  ****         "
    .bitmap "       ******           "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .byte 0
;
; Sprite #3
;
    .bitmap "                        "
    .bitmap "                        "
    .bitmap " ******************     "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap " ******************     "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap " ******************     "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap " ******************     "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap " ******************     "
    .bitmap "                        "
    .bitmap "                        "
    .byte 0
;
; Sprite #4
;
    .bitmap "        *****           "
    .bitmap "        **  **          "
    .bitmap "        **  **          "
    .bitmap "        ** **           "
    .bitmap "        ****            "
    .bitmap "      *****             "
    .bitmap "    ***  ******         "
    .bitmap "   **   **** ***        "
    .bitmap "   ** **  **   **       "
    .bitmap "   **  ** **    **      "
    .bitmap "    ***   **  ***       "
    .bitmap "      *********         "
    .bitmap "           **           "
    .bitmap "       ** ***           "
    .bitmap "       ****             "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .byte 0
;
; Sprite #5
;
    .bitmap "      *******           "
    .bitmap "    ***    ****         "
    .bitmap "   **        ***   **   "
    .bitmap "   **         ***  **   "
    .bitmap "    ****      ***       "
    .bitmap "    ****      ***       "
    .bitmap "    ****      ***  **   "
    .bitmap "              ***  **   "
    .bitmap "              **        "
    .bitmap "             ***        "
    .bitmap "            ***         "
    .bitmap "           ***          "
    .bitmap "          ***           "
    .bitmap "        ****            "
    .bitmap "     *****              "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .byte 0
;
; Sprite #6
;
    .bitmap "   *** **  ****         "
    .bitmap "   *** *****  **        "
    .bitmap "   *** ****    **       "
    .bitmap "   *** ****    **       "
    .bitmap "   *** **      **       "
    .bitmap "   *** **     **        "
    .bitmap "   *** ********         "
    .bitmap "   *** **               "
    .bitmap "   *** **               "
    .bitmap "   *** ********         "
    .bitmap "   *** **     **        "
    .bitmap "   *** **      **       "
    .bitmap "   *** ****    **       "
    .bitmap "   *** ****    **       "
    .bitmap "   *** *****  **        "
    .bitmap "   *** **  ****         "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .bitmap "                        "
    .byte 0
